### ISSUE TITLE
IsInvalidProperty is always true

### ISSUE THREAD

**Issue by delboj** [PyramidTechnologies/ThermalTalk#6]
I have a POG model with the latest firmware.
It prints everything ok but I can't poll to check if printer is working or not. Every time I call the getStatus method the IsInvalidReport property is always true

**Comment by corytodd** [comment]
Hello, please answer these questions from the issue template:

1. Confirm that the white sticker on the bottom says PHX-POG
2. What firmware are you using?
3. USB or RJ-45 serial?

**Comment by delboj** [comment]
1. It does
2. PHXv119.pti - downloaded that file from pyramidacceptors.com USA-firmware
3. I use RJ-45 serial, tried it with USB too. When I was using USB connection it polls for about 5-10 seconds but every time HasError property is true, everything else is false. Then after that I just start getting IsInvalidProperty as true again, nothing else.

And I also noticed that it can only print with RJ-45 serial connection.

**Comment by corytodd** [comment]
Thanks for confirming.

PHXv119 does not support the full ESC/POS command set. You will need to contact support@pyramidacceptors.com to see about getting the correct model/firmware to handle what you need.
